### PR TITLE
Milestone 2- Friendship-v1

### PR DESCRIPTION
**Pull request by DanSam5K**
In this milestone 
- Was able to design ERD for the database with Lucichart
- I was able to configure the project to reflect the recent files updates dependencies.
- Configure and create files migration to use Pg for development and migrate to a database
- Generate friendship model, active-record associations and add helper methods for friendship in the user model
- Update rubocop and fix linters error.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 
## Hello @DanSam5K, you've done good job so far especially with your models :+1: 

### To improve:

- [x] You have some uncommitted code.
- [x] User should be able to invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User should be able to see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Posts timeline includes posts written by logged-in user and their friends currently in your timeline a user can see posts also from other users which are not their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] At this stage you should add unit and integration tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### If you have any questions with regards to the requirements please add a comment here and I will try to reply ASAP.

# HAPPY CODING :computer: :desktop_computer:

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes Required 🔴
Hey @DanSam5K, you have done a good job so far, especially with the tests you added.

**To improve**
- [x]  Remove the commented code in one of the test files.
- [x]  User should be able to invite friends, I wasn't able to see a button to invite for friendship, see the image below:
friendship

- [x] Because of the issue above it's impossible to review for other issues, for this reason, you should refer to the previous reviewer's comments.

If you have any questions with regards to the requirements please add a comment here and I will respond.

# Cheers
# Happy coding
Elisha

**Review by Georjane — CHANGES_REQUESTED** [review]
### Hello @DanSam5K, ✋🏽 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing most of the requested changes, but there are still some which aren't addressed yet. You are almost there.

## Required Changes ♻️
I noticed that if user 1 sends a request to user 2, when user 2 accepts this request, they become friends, which is what we expect, but we have the following issue:  
- [x] There is no notice that shows that they are now friends. i.e besides the name of user 1, we should see either `Friends` if they are friends or `Send Friend Request` if they are not friends.
- [x] I also noticed that even after user 2 accepts the friend request of user 1, user 2 is still able to see and click the `Send Friend Request` button to user 1. But this is not supposed to be possible because they are already friends.
- [x] Even though user 2 accepted the friend request of user 1, the posts timeline of user 1 does not include posts written by their friends, user 2. But this works just fine for user 2 because he was the one that sent the request. But there seems to be a problem for user 1 who accepted the request

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [x] Displaying the name of the logged-in user at the navbar so we can easily identify who is logged in at any time

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**Comment by DanSam5K** [comment]
Noted @Georjane, Will try and give it my best and see it resolved.
Thank you for your response and feedback.

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED👍️👍️👍️**

Hello @DanSam5K 

Great work making the requested changes.👏️👏️

You can merge👍️👍️

Happy coding💻️💻️

**Comment by DanSam5K** [comment]
Thank you @NtwaliHeriter.

**Pull request merged**
