### PR TITLE
Milestone 4 - Friendship v2

### PR DESCRIPTION
**Pull request by DanSam5K**
In this milestone
- Try to implement friendships with 2 rows for mutual friendship.
- Fix metric complexity issues

### CODE REVIEW

**Review by cyonii — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️✍️

Hello team, this is a great start. Keep up the energy.

### TO HIGHLIGHT
- Your commit messages are crystal clear ✅

### TO IMPROVE (MANDATORY)
- [x] When friendship is confirmed, an additional row with reversed user-friend pair is created. Currently, your app doesn't create a reversed row when friendship is confirmed. Take for instance the snippet below:
```ruby
# Friendship model

def confirm_friend
    self.update_attributes(confirmed: true)
    Friendship.create!(
        friend_id: self.user_id,
        user_id: self.friend_id,
        confirmed: true
    )
end
```
- [x] `PostsController#index` displays posts in a timeline (current_user's own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)).Currently all posts are displayed for every user. Please fix this.


### NICE TO HAVE
> #### AFTER IMPLMENTING REVERSED ROW
Once you implement the creation of reversed row when friendship is confirmed, you can also make the following changes to your models to make querying easier.
- [x] We can find user's friends only by user_id in the friendships table
  ```ruby
  # User model

  has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
  has_many :friends, through: :confirmed_friendships
  ```
- [x] `User#pending_friends` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

- [x] `User#friend_requests` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [x] in order to get all posts written by users on their friends, you can use a simple method in the User model (in order to NOT do it with Enumerable)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

> #### <br>Feel free to leave a comment or question if something is not clear.<br> Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)<br><br>

**Comment by DanSam5K** [comment]
Thank you for the kind feedback.
Will implement the changes right away!

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: 
----------------
Hello @DanSam5K, great job you are doing so far in this milestone. :clap: :muscle: 
There is only one thing to fix to complete this milestone see it below. :eyes: :point_down: 
-----------------

- [x] I will only be able to see posts from my friends and my own post. Currently, OI can see posts from no friend. 

timeline

--------------
Make this minor change and send it again for another review :+1: :100: 
HAPPY CODING!!

CavernousEnergeticBluetonguelizard-size_restricted

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL BUT IMPORTANT
- [x] Please add negative unit test cases and also add integration tests for authentication and friendship functionality. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png).
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Comment by DanSam5K** [comment]
- Will Implement that right away! 🤝   🎉

**Pull request merged**
